name: Cypress Tests
on: [push]
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2
 
     - name: Run Cypress Test
       uses: cypress-io/github-action@v4
       with:
         command: npx cypress run
         browser: chrome
         
     - name: Send mail on release
       if: failure()
       uses: dawidd6/action-send-mail@v3
       with:
         server_address: smtp-mail.outlook.com
    # Server port, default 25:
         server_port: 587
         # Optional whether this connection use TLS (default is true if server_port is 465)
         # secure: true
         # Optional (recommended) mail server username:
         username: ${{secrets.MAIL_USERNAME}}
         # Optional (recommended) mail server password:
         password: ${{secrets.MAIL_PASSWORD}}
         # Required mail subject:
         subject: Check Visa Bulletin
         # Required recipients' addresses:
         to: priyan.prabhu@gmail.com
         # Required sender full name (address can be skipped):
         from: prabhu.shan@outlook.com
